import type { Metadata } from 'next';
import { Barlow } from 'next/font/google';

import { Sidebar } from '@vat/components/layout/sidebar/Sidebar';
import { cn } from '@vat/lib/utils';

import './globals.css';

const barlow = Barlow({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  style: 'normal',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='en'>
      <body className={cn(barlow.className, 'bg-base-dark-bg-1')}>
        <Sidebar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
